language: objective-c
osx_image: xcode10.3
cache:
    directories:
      - /nix/ 
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
install:
  - curl https://nixos.org/nix/install | sh
  - source ~/.nix-profile/etc/profile.d/nix.sh
  - carthage checkout
script: nix-shell --pure --run ./scripts/test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./fastlane/test_output/
