language: objective-c
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
install:
  - bundle install
  - carthage checkout
script: ./scripts/test

after_success:
  - bash <(curl -s https://codecov.io/bash)
