language: objective-c
osx_image: xcode8
xcode_project: TDRedux.xcodeproj
xcode_scheme: TDRedux

script:
  - xcodebuild \
    -project TDRedux.xcodeproj \
    -scheme TDRedux \
    -destination "OS=10.0,name=iPhone 6s Plus" \
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES \
    GCC_GENERATE_TEST_COVERAGE_FILES=YES \
    test | xcpretty -c
