# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
workspace = "TDRedux.xcworkspace"

platform :ios do
  desc "Run tests on iOS"
  lane :test do
    scan(
      scheme: "TDRedux-iOS",
      workspace: workspace,
      clean: true,
      code_coverage: true
    )
  end
end

platform :macos do
  desc "Run tests on macOS"
  lane :test do
    scan(
      scheme: "TDRedux-macOS",
      workspace: workspace,
      clean: true,
      code_coverage: false
    )
  end
end

platform :watchos do
  desc "Run tests on watchOS"
  lane :test do
    scan(
      scheme: "TDRedux-watchOS",
      workspace: workspace,
      clean: true,
      code_coverage: false
    )
  end
end

platform :tvos do
  desc "Run tests on tvOS"
  lane :test do
    scan(
      scheme: "TDRedux-tvOS",
      workspace: workspace,
      clean: true,
      code_coverage: false
    )
  end
end
